import Header from "./components/Header";
import ProductCard from "./components/ProductCard";
export const metadata = {
  title: 'Beydamax',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <main>
      < Header />
      {/* CARDS */}
      <div className="py-3 px-36 mt-10 flex flex-wrap justify-center">
        < ProductCard />
      </div>
      {/* CARDS */}
    </main>
  )
}
